### ISSUE TITLE
Not able to edit on iOS:  undefined is not an object (evaluating 'o.left')" 

### ISSUE THREAD

**Issue by adamgins** [froala/froala-reactive#12]
Hi, I am not sure what I have messed up, as it was all working. The only thing I have really been playing with is the license keys.

on iOS Safari, when I click into a editable field I see the following on the console (done via Cable to Mac):
"TypeError: undefined is not an object (evaluating 'o.left')" 

![image](https://cloud.githubusercontent.com/assets/7233741/6014861/3a591762-abc0-11e4-897f-98252b7a59f9.png)

**Comment by rjsmith** [comment]
No idea, sorry.  Unlikely to be an issue with froala-reactive itself.  Suggest you re-post on meteor-froala or on their wysiwyg repo, with enough additional information (steps to reproduce, your code, environment etc etc) that someone might be able to help you.

**Comment by adamgins** [comment]
Thanks... ok I am in discussion with @stefanneculai I seem to have a clash with Froala and hammerjs... just trying to work it out.
