### ISSUE TITLE
parsing saved html

### ISSUE THREAD

**Issue by amazingBastard** [froala/froala-reactive#13]
Hey there,

Great package, having a lot of fun working with it. Just one question, how can I parse the saved HTML in a template. I like to make a preview mode but the saved HTML is returned as a string. Is there a way to parse the string to html? Thanks for the help.

**Comment by rjsmith** [comment]
Hi,

Include the content in a Blaze [triple - curly tag](https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md#triple-braced-tags), like this:

```html
<span id='preview'>{{{someDocument.someHTMLContent}}}</span>
```

Hope that is what you were looking for. If so, please close this ticket, thanks.

**Comment by amazingBastard** [comment]
That's perfect. Thanks a lot. I should probably read through those docs in more detail. Ticket closed, thanks again for the great package.
