### ISSUE TITLE
Can I custom my buttons?

### ISSUE THREAD

**Issue by chenkaiC4** [froala/froala-reactive#14]
Hi, I want to custom my buttons.
I refer to [custom buttons](https://editor.froala.com/examples/custom-toolbar)
```
<script>
  $(function() {
    $('.selector').editable({
      // Set custom buttons with separator between them.
      buttons: ['undo', 'redo' , 'sep', 'bold', 'italic', 'underline']
    })
  });
</script>
```
so my code, e.x. `myButtons = ['bold', 'html', 'table']`,:
```
{{> froalaReactive _onblur=updateMD5 keyChain=keyChain inlineMode=false _value=value buttons=myButtons}}
```
it doesn't work.

**Comment by rjsmith** [comment]
Hi. Please clarify "it doesn't work". Do you see buttons at all? Any errors printed in the browser console? Please help me to help you.  How do you define your 'myButtons' property?   As a template helper? Or in the template's data context?

**Comment by dubvfan87** [comment]
I'm having the same issue.

{{> froalaReactive buttons=["bold", "italic", "underline"] height=200 theme="dark" inlineMode=false _onbeforeSave=doSave _value=myDoc.myHTMLField}}

I still see all of the default buttons. However if I do:

{{> froalaReactive buttons=false height=200 theme="dark" inlineMode=false _onbeforeSave=doSave _value=myDoc.myHTMLField}}

It shows no buttons as expected.

**Comment by rjsmith** [comment]
Try providing the buttons value from a template helper function that returns the array of button names you want to use.

**Comment by dubvfan87** [comment]
That worked, thank you!

On Sun, May 24, 2015 at 4:23 PM, Richard Smith <notifications@github.com>
wrote:

> Try providing the buttons value from a template helper function that
> returns the array of button names you want to use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/froala/froala-reactive/issues/14#issuecomment-105059130>
> .
>



-- 

Matt Moyles
http://mattmoyles.com
