### ISSUE TITLE
precedence of blur vs other click events

### ISSUE THREAD

**Issue by adamgins** [froala/froala-reactive#15]
HI, I seem to have a tussle between two competing items/events that seems to be causing the `_onblur=doSave` not to fire. 

If I click out of my `froalaReactive` which has the above event set onto a general area on the page, all works fine. The doSave function is called. 

I have some other sibling items on the page that do things when clicked (they have a stopPropagation call) and when I clicked, the onblur event never seems to fire as the 'click' event gets fired before `onblur` and changes a param that hides the template (so the blur event never gets to fire). 

is there anyway to ensure I get the blur event before the click elsewhere on the page?

**Comment by rjsmith** [comment]
Hi,
I suspect this is a not meteor - specific issue, or an issue specific to froala-reactive.  However, maybe you could look at adding some guard code in the onDestroyed() function for the templates hosting a froala-reactive instance, to see if you can trap scenario where there are unsaved changes in the editor,and then invoke your save logic?

**Comment by stefanneculai** [comment]
This should be fixed in V2.

**Comment by rjsmith** [comment]
Indeed, it looks like onblur is firing before other click events, that's
really cool, thanks
