### ISSUE TITLE
AutosaveInterval

### ISSUE THREAD

**Issue by dakota11** [froala/froala-reactive#16]
I'm trying to get autoSaveInterval to work with no luck.  Here's what's in my template file...

{{> froalaReactive   autosaveInterval=2500 _onbeforeSave=doSave  inlineMode=false  _value=this.text}}

When I call doSave with : $('.froala-box').editable('save')
everything works...

But not doSave doesn't seem to be getting called with autosaveInterval.

Any ideas?

**Comment by rjsmith** [comment]
Hi,
There are two settings that are needed to make this work:

```
{{> froalaReactive autosave=true autosaveInterval=2500 .... }}
```

See https://www.froala.com/wysiwyg-editor/docs/options#autosave

Let me know if this works for you, then I can close this issue.

**Comment by dakota11** [comment]
It works, yes.  Thanks for the clarification.

**Comment by tarzak** [comment]
hello, are there any changes? Does not work for me.

**Comment by rjsmith** [comment]
Hi
No changes to this wrapper package recently. You will have to provide more
info if I will have a chance to help you.
