### ISSUE TITLE
Upload Image to GridFS

### ISSUE THREAD

**Issue by daslicht** [froala/froala-reactive#19]
Hello,
how would we configure Froala so that we can store the Images in GridFS?
eg: imageUploadURL ?
please?

**Comment by rjsmith** [comment]
Hi,
I haven't looked at this myself yet, though it is on my own product roadmap in the future.

There seems to be two possible types of approaches:
1. Work with the FE ajax - based image upload feature, by implementing a non-DDP ajax http server routes in your server-side Meteor application to save and retrieve images (which would use server-side GridFS to persist  / retrieve the image)
2. Intercept / override the default FE client-side ajax - based image handling (hooking into the FE `beforeImageUpload` event), using the GridFS client-side API to save the images. I don't know how to embed a link / reference to the image in the FE markup such that it will attempt to retrieve the image again when it is displayed...

My guess is that the first approach will be easiest.

**Comment by daslicht** [comment]
Ok , I will try to add a upload route

**Comment by daslicht** [comment]
Do you have any idea where to find an working example how to setup a iron router router to handle file uploads?

**Comment by daslicht** [comment]
Hello,
I have managed to upload an Image from Froala, but the returned editor seams to be not valid:

According to the Froala Docs, this way we should be able to insert an image at the curret cursor:
```
		beforeImageUpload: function() {
			var self = this;
		    return function (e, editor, img) {
				var url ="http://localhost:3000/cfs/files/images/MXsbirDwadqrL6fRy/BaumGeist.JPG"; //dummy

				editor.editable('writeImage', url, true);
```

I just get:
```
Uncaught TypeError: undefined is not a function 
```

**Comment by daslicht** [comment]
I got it now working with the non reactive froala:

```
$('.froala').on('editable.beforeImageUpload', function (e, editor, images) {
		    	var self = $(this);
				console.log(this);
				console.log(editor);
				//var url ="http://superdevresources.com/images/meteor/meteor-free-ebooks-tutorials.png";
				
				Images.insert(images[0], function (err, fileObj) {
		      		//console.log("editor ",  editor);
					//console.log("after insert:", fileObj._id);
					Tracker.autorun(function (c) {
			          fileObj = Images.findOne(fileObj._id);
			          var url = fileObj.url();
			          if (url) {
						self.editable('writeImage', url, true);
			          	//editor.editable('writeImage', url, true);
			          	console.log("URL: ",url);
			          	//$("#summernote").summernote("insertImage", fileObj.url(), "Image Title"); 
			            //editor.insertImage($editable, url);
			            var response = {
			            	link: url
			            }
			            return response;
			            c.stop();
			          }
			        });
				});
			});
```
