### ISSUE TITLE
Froala options (plainPaste, useFrTag) partly ignored and (Chrome-only) inline styles

### ISSUE THREAD

**Issue by dave-buzzy** [froala/froala-reactive#20]
Hi

I'm having an issue with the froala-reactive editor in our app that's manifesting only in Chrome so far (using v44.0.2403.89 at the moment but same issue existed earlier). We call the editor with a bunch of options set like so:
![screen shot 2015-07-23 at 4 53 56 pm](https://cloud.githubusercontent.com/assets/8966637/8846952/4c0c535c-315d-11e5-819a-e3888d52a3bb.png)

Note plainPaste is set to true - however, when copy/pasting content in Chrome, the editor seems to grab inline styles corresponding to the source content's display, and includes them with the pasted item - like so:
![screen shot 2015-07-23 at 4 55 05 pm](https://cloud.githubusercontent.com/assets/8966637/8847024/cfc8bb0e-315d-11e5-8673-36c7c92a9225.png)
![screen shot 2015-07-23 at 4 55 55 pm](https://cloud.githubusercontent.com/assets/8966637/8847028/d4dd3f34-315d-11e5-88d6-5477720acde8.png)

The second list above - hard to see - has a white background as opposed the very pale gray of the body as a result of all the inline styles it's had assigned when pasting. This seems to only happen in Chrome, and with block level elements like `<ul>` or `<ol>` - but strangely not with nested block items like `<li>`.
 
When pasting other rich content in chrome - eg inline bolded text -  the `<strong>` tags are stripped out and replaced with `&nbsp;` (all good so far) - but Chrome ignores them in its rendering - see the words 'WhenplainPasteoption' in the screen capture and inspector above. This doesn't happen in other browsers - eg Safari, Firefox - they respect the spaces.

**Possibly related:** Not all our options for Froala as defined at top seem to be getting applied - eg `useFrTag` should be false by default, and I've explicitly set it to false, but block level elements are still getting a class of `fr-tag` applied inside the editor. So something is setting this to true...

**Comment by rjsmith** [comment]
Hi

FroalaReactive itself is a thin layer over the FE JavaScript codebase. I
suggest you raise your issues against the main FE github repo so the FE
folks will pick up your concerns...

**Comment by dave-buzzy** [comment]
Thanks - I've raised this over at the meteor FE repo.
