### ISSUE TITLE
Is latest package on Atmosphere?

### ISSUE THREAD

**Issue by adamgins** [froala/froala-reactive#21]
Hi, I know you updated Github... thanks heaps!!!

For some reason this is not flowing through to Atmosphere, see: 
![image](https://cloud.githubusercontent.com/assets/7233741/10505754/8e24b8e2-735c-11e5-8332-b77734da5040.png)

Any ideas pls?
https://atmospherejs.com/froala/editor-reactive
@rjsmith @stefanneculai

**Comment by rjsmith** [comment]
Hi

I'm Planning on publishing this on or before this weekend. Got to work on
one more issue with the update (FE v2 has removed the "option" method)

**Comment by adamgins** [comment]
@rjsmith awesome - sounds great. Thanks!!!

**Comment by rjsmith** [comment]
Published 2.0.0-rc.1 on atmosphere

**Comment by adamgins** [comment]
Thanks
