### ISSUE TITLE
Is example right?

### ISSUE THREAD

**Issue by adamgins** [froala/froala-reactive#22]
@rjsmith thanks for the update
Just checking is the example in the readme correct?

```
Template.myTemplate.helpers({
  getFEContext: function () {
    const self = this;
    _value=self.myDoc.myHTMLField,
    "_onsave.before": function (e, editor) {
      // Get edited HTML from Froala-Editor
      var newHTML = editor.html.get();
      // Do something to update the edited value provided by the Froala-Editor plugin, if it has changed:
      if (!_.isEqual(newHTML, self.myDoc.myHTMLField)) {
        console.log("onSave HTML is :"+newHTML);
        myCollection.update({_id: self.myDoc._id}, {
          $set: {myHTMLField: newHTML}
        });
      }
      return false; // Stop Froala Editor from POSTing to the Save URL
    },
  },
})
```

Sorry, was a bit unclear on what I should be returning  from a function like this?

**Comment by rjsmith** [comment]
Doh! The helper function should return an object containing the
froala-reactive context properties (_value etc). Will fix up the Readme
later today if I have time...

**Comment by adamgins** [comment]
@rjsmith thanks. 

does the _onsave.before need to `return false;` after the save code?
also, so for  `blur` do we use the same `_onblur`, as before ?

**Comment by rjsmith** [comment]
Hi

Froalareactive just does a pass through of 'on' FE event handlers through
to FE. Please refer to the FE v2 documentation for the supported  event
names and behaviour :

https://www.froala.com/wysiwyg-editor/v2.0/docs

**Comment by adamgins** [comment]
Thanks
Ok, kinda have it working ... well it seems to work (ie I can edit the field) but I do see this on the console:

```
MARKER TypeError: Cannot read property 'nextSibling' of undefined
    at Object.e [as insert] (http://localhost:3000/packages/froala_editor.js?3ec25e8b98ecf1662b6905ff9bb8a329cee1feb4:32:10133)
    at i (http://localhost:3000/packages/froala_editor.js?3ec25e8b98ecf1662b6905ff9bb8a329cee1feb4:32:26819)
    at HTMLDivElement.<anonymous> (http://localhost:3000/packages/froala_editor.js?3ec25e8b98ecf1662b6905ff9bb8a329cee1feb4:32:27099)
    at HTMLDivElement.jQuery.event.dispatch (http://localhost:3000/packages/jquery.js?bd30605bc9f8429d01bae2d29081902d10a6c400:4699:9)
    at HTMLDivElement.elemData.handle (http://localhost:3000/packages/jquery.js?bd30605bc9f8429d01bae2d29081902d10a6c400:4367:28)
```

Any ideas pls?

**Comment by adamgins** [comment]
@rjsmith looks like similar to this one https://github.com/froala/wysiwyg-editor/issues/836

**Comment by rjsmith** [comment]
Yes, its a FE issue.

**Comment by rjsmith** [comment]
Committed README change. Will not push new package to atmosphere yet ... hope FE will publish their final V2 release very soon.

**Comment by adamgins** [comment]
Thanks. Are you seeing 'nextsibling' error. Not sure if you need to update this to rc3?

Adam Ginsburg
adam.ginsburg@buzzy.buzz
tel: +61 411 151 732
http://buzzy.buzz

**Comment by rjsmith** [comment]
Yes me too. Waiting for @stefanneculai to update froala:meteor package (need this committed change https://github.com/froala/wysiwyg-editor/commit/30ce3d42d58efc4ac934aaf0670f08a9eccfba97)
