### ISSUE TITLE
Issue with onDestroyed and trying to call 'save.save' or 'save.force'

### ISSUE THREAD

**Issue by adamgins** [froala/froala-reactive#23]
Thanks for the new version. Seems to be working well, bar a few key issues:

I am trying to save the content when then item is destroyed, however it seems like the function `_onsave.before` never gets triggered.

I have tried a few options. Not sure if the JS is gone by the time the event fires, so there's no code to fire?

```
Template.contenteditable.onDestroyed(function(){
	console.log("onDestroyed")
	//this.$('div.froala-reactive-meteorized').froalaEditor('events.trigger', 'froalaEditor.destroy',[],true);
	this.$('div.froala-reactive-meteorized').froalaEditor('save.force');

```

I if I enable the `autosave` the `_onsave.before` gets called, however the cursor/caret goes back to the start of the field with each autosave. 

I have looked at some of the examples , for example: http://stackoverflow.com/questions/32617361/retain-caret-position-in-froala-editor-after-html-set-or-snapshot-restore and tried to implement in V2, however the "setHTML" bit is never done as Meteor takes care of that right???

Any ideas pls?

**Comment by rjsmith** [comment]
Hi,
Hmm. Well, I suggest you fork this project and add in your saving logic within this try block in the onDestroyed callback within the froala-reactive code, just for an experiment:

https://github.com/froala/froala-reactive/blob/master/froala-reactive.js#L117-L119

If that seems to work (ie the editor still has the content at that point), you could introduce the ability to specify a callback from the calling template that is invoked at that same point in the onDestroyed callback.  I'd be happy to accept a PR. 

re: cursor jumping on autosave .. yeah I know, it's annoying. I have tried a couple of things on V2 mucking about with markers, but nothing satisfactory so far.

**Comment by stefanneculai** [comment]
@rjsmith is the reactive component doing any changes while typing? Both you and @adamgins mention about a cursor position loss on autosave, but we don't have any such report. Could you make a jsFiddle for it?

**Comment by rjsmith** [comment]
Hi,

I haven't seen @adamgins code, but what I have in my code is a sequence
like:
1. User types something into Froala Reactive field
2. autosave interval times out, which triggers a callback into Meteor code
which saves the field contents to the server
3. Server persists the altered value, which triggers Meteor's reactivity to
publish the altered field back to the client,
4. Froala Reactive is automatically triggered to update the html inside the
FE editor using html.set

This causes the cursor to jump back to the start of the field (as far as FE
is concerned, it has just got new content via html.set).

I think the only solution is to use FE's markers feature., I played around
with this briefly on the V2 editor, but have not yet had enough time to
look at it more.  Basically, we need a way for FE to save the current
cursor position when a save event is triggered: this html gets added to the
saved content, does the roundtrip to the Meteor server and back, then FE
changes the cursor position back to the previous position when it gets the
updated html

**Comment by stefanneculai** [comment]
I understand the problem. Wouldn't it work for you just to use html.set method only if the HTML from the server is different than the one inside the editor?

**Comment by rjsmith** [comment]
HI,

@adamgins I think I have resolved the problem of the jumping cursor for using the autosave function, at least in my own wrapper code around froalaReactive.  Take a look at the new 2.0.1_1 version I have just pushed to atmosphereJS.com

Set the `_keepMarkers=true` property in the froalaReactive context.
Then make sure you call the FE `selection.save` method immediately prior to extracting the html out of the wrapped FE instance using the `html.get(true)` method (so it preserves the embedded marker spans)

**Comment by rjsmith** [comment]
Closing
