### ISSUE TITLE
Import and Export Selection, selection.set()

### ISSUE THREAD

**Issue by Valentin-Seehausen** [froala/froala-reactive#25]
Hey, great Editor, thanks, I think we are gonna become customers!

But one really important issue: I want to ex- and import the selection. It is not sufficiant enough to save the selection into html, because the HTML gets saved to the database "in between". There is a method selection.get(), could you implement something like selection.set()? That would be awesome!

**Comment by rjsmith** [comment]
hi,
I don't work for or provide support for Froala, I just wrote this wrapper
package for Meteor, but glad you find it useful! If you have any general
queries about Froala Editor's API, please raise it in the main github repo
for the V2 editor    here: https://github.com/froala/wysiwyg-editor

I don't understand what you mean by "ex- and import the selection".
Perhaps you could provide a more detailed step - by - step example of what
you are trying to achieve and I'll see if froala reactive can help...

**Comment by Valentin-Seehausen** [comment]
Hey, thanks for the reply!

Ah, ok, it didn't know, you were not working for the company (it is a commercial one). Well, when I want to insert HTML, so I have to save the selection with editor.selection.save() and when I am finished with my HTML generating method, I will editor.section.restore(), so the HTML gets pasted to the cursor, that has been in the editor, before i blured it (to open the modal, etc).

The point is, that froala editor saves the selection inside the HTML, and other editors, like medium-editor, save the selection as a array with numbers, that show, where the cursor is. And this array can be im -and exported. I want to have this array.

But anyway: Thangs for providing this package, it works perfect!
