### ISSUE TITLE
Issue with hitting return 

### ISSUE THREAD

**Issue by adamgins** [froala/froala-reactive#26]
Please see https://github.com/froala/meteor-froala/issues/20 not sure if should have posted here instead?

**Comment by rjsmith** [comment]
Hi,

Unlikely to be related to this package, as its code does not have any
special 'enter' key handling.

Have you experimented with FE's 'enter' option?

**Comment by rjsmith** [comment]
Closed
https://github.com/froala/meteor-froala/issues/20#event-539096811
