### ISSUE TITLE
Issue with multiple editors being destroyed

### ISSUE THREAD

**Issue by adamgins** [froala/froala-reactive#30]
Hi, We have a page with multiple Froala Editors on the screen. If one of them is destroyed the others die too.

@rjsmith @stefanneculai Is there something in the Froala-reactive ondestroy that's disabling/killing other instances on the page https://github.com/froala/froala-reactive/blob/master/froala-reactive.js#L115 ?

**Comment by adamgins** [comment]
@stefanneculai @rjsmith hi, wondering if you've addressed this specifically in the 2.2.2? I could not see anything in the changelog. Also not sure if it's something that was introduced in 2.2.0 as I saw some stuff around destroy and cleanup mentioned `Automatically turn off all events on destroy.`  as per https://www.froala.com/wysiwyg-editor/changelog ?

**Comment by rjsmith** [comment]
Hi,

I suspect this line (and the one below it) are to blame ...

https://github.com/froala/froala-reactive/blob/master/froala-reactive.js#L142

I added this line to workaround an issue in the FE editor: https://github.com/froala/wysiwyg-editor/issues/844
But looks like it has been fixed, so I will try it out this evening and see if I can remove those 2 lines.

**Comment by rjsmith** [comment]
Hi @adamgins .. please try the new v2.2.2_1 version to see if that sorts out your problem here.  If not, maybe you can explain in more detail what behaviour you are seeing.

**Comment by rjsmith** [comment]
assume fixed.
