### ISSUE TITLE
Changing image alignment leaves image tool in previous position

### ISSUE THREAD

**Issue by barrydoyle18** [froala/froala-reactive#31]
Whenever I drop an image in my editor an image editing UI appears for the image, when the image's alignment changes the UI remains in the initial position of the image and doesn't close like it should.  Is this problem just occurring with me or are others experiencing it too?

**Comment by rjsmith** [comment]
Hi Barry,

I suggest you raise this issue on the main Froala Editor repo:
https://github.com/froala/wysiwyg-editor/issues, not here. Froala Reactive
is just a Meteor - specific Blaze template wrapper around the FE editor.
This type of issue is not going to be anything to do with this wrapper
package.  If you can describe a clear set of test steps, so much the
better.  I often try to reproduce issues using their own demo examples
here: https://www.froala.com/wysiwyg-editor/docs/examples ... much easier
than setting up your own example on something like jsFiddle.

Regards,
Richard

**Comment by barrydoyle18** [comment]
I'll post my issue there then, thank you
