### ISSUE TITLE
save on clicking a button

### ISSUE THREAD

**Issue by Nisthar** [froala/froala-reactive#32]
How can i save the content inside the froala editor on clicking a button instead of autosave?

**Comment by stefanneculai** [comment]
See: https://www.froala.com/wysiwyg-editor/docs/concepts/save-button

**We're using this repo for bug tracking only and not for support. For support, please contact us via our website. Thank you.**

**Comment by Nisthar** [comment]
@stefanneculai Oh Sorry, I didn't knew that.

Anyway, Whats the meteor way of doing this? I am not sure if the article you shared will work on meteor.

**Comment by stefanneculai** [comment]
Here is how you can invoke a method https://github.com/froala/froala-reactive#methods.

**Comment by Nisthar** [comment]
@stefanneculai Thanks. I am hopping this works. 
```
Template.editor.events({
'click #submit': function(e,t){
e.preventDefault();
t.$('div.froala-reactive-meteorized').froalaEditor('save.before');
}
});
```
is there any way i can disable the default autosave?

**Comment by Nisthar** [comment]
@stefanneculai  Solved it :+1:

Thanks for your help.

**Comment by ldong** [comment]
For anyone who encountered this issue, here's my code snippet for it.

```javascript
Template.Post.events({
  'click .save-post': function (event, template) {
    event.preventDefault();
    console.log('save triggered');
    template.$('div.froala-reactive-meteorized-override').froalaEditor('save.save');
  }
});
```
