### ISSUE TITLE
Exception from Tracker recompute function:

### ISSUE THREAD

**Issue by tarzak** [froala/froala-reactive#33]
Looks like if I provide some variables to froala config, it invokes exception:
```
Error: Method snapshot.restore does not exist in Froala Editor.
    at Function.error (jquery.js:247)
    at HTMLDivElement.<anonymous> (froala_editor.min.js:7)
    at Function.each (jquery.js:384)
    at jQuery.each (jquery.js:136)
    at jQuery.a.fn.froalaEditor (froala_editor.min.js:7)
    at froala-reactive.js:102
    at Object.Tracker.nonreactive (tracker.js:603)
    at .<anonymous> (froala-reactive.js:79)
    at view.js:199
    at Function.Template._withTemplateInstanceFunc (template.js:465)
```
If I remove that variables before transfer to froala, looks like no exception being invoked.
I don't use `snapshot.restore`. Can I have some tips about what it could be?

**Comment by rjsmith** [comment]
What version of the froala:editor-reactive package are you using in your Meteor application?

**Comment by tarzak** [comment]
@rjsmith the latest 'froala:editor-reactive@2.3.4', and API v2

**Comment by rjsmith** [comment]
OK. I haven't used this feature for a while, but I just created a simple project, and I can execute the code to execute without any problems when changing a FE option:

```html
<head>
  <title>froala-reactive-33</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>

  {{> hello}}
</body>

<template name="hello">

  <button>Click Me</button>

  {{> froalaReactive getFEContext}}

</template>
```

```javascript
import { Template } from 'meteor/templating';
import { ReactiveVar } from 'meteor/reactive-var';

import './main.html';

Template.hello.onCreated(function helloOnCreated() {
  // counter starts at 0
  this.counter = new ReactiveVar(14);
});

Template.hello.helpers({
  getFEContext() {
    return {
      _value: "foo",
      fontSizeDefaultSelection: Template.instance().counter.get().toString(),
    };
  },
});

Template.hello.events({
  'click button'(event, instance) {
    // increment the counter when button is clicked
    instance.counter.set(instance.counter.get() + 1);
  },
});

```

Maybe you could post some of your code here, especially the code that passes the data context to the {{> froalaReactive}} component?  What are you trying to achieve? Maybe there is another way of doing it...

**Comment by tarzak** [comment]
@rjsmith thank you for fast respond, but as I have few files that relate to current implementation, I decided just cut these properties that invoke collision and it helped in this situation.
