### ISSUE TITLE
ReferenceError in helper

### ISSUE THREAD

**Issue by payner35** [froala/froala-reactive#7]
i dont seem to have 'e' or 'editor' in scope in my helper class..    i get an error..
Exception in template helper: ReferenceError: e is not defined

    doSave: ->
		console.log "doSave"
		#https://github.com/froala/froala-reactive

		console.log e
		console.log editor

		self = this
		return (e, editor) ->
			# Get edited HTML from Froala-Editor
			newHTML = editor.getHTML()

any idea on what i am doing wrong. ?

**Comment by rjsmith** [comment]
Hi,

The `e` (event) and `editor` arguments are only in scope inside the function returned from the helper function.  The purpose of the `doSave` helper is to return a function that will be used as a Froala Editor event callback.

So, if you moved the three `console.log` statements above to inside the return function in your example code, they would print out when the callback is triggered by Froala Editor.

There is an example in the README [here](https://github.com/froala/froala-reactive#basic-usage).  Also take a look at the Froala Editor events documentation [here](https://editor.froala.com/events).

Hope that helps, please close this issue if it does  :-)

**Comment by payner35** [comment]
ok noted..

the problem i am having then is that the  "console.log editor" is never reached.

    Template.saladInfo.helpers

	doSave: ->
		console.log "doSave"
		#https://github.com/froala/froala-reactive

		self = this
		(e, editor) ->
			console.log editor
			# Get edited HTML from Froala-Editor
			newHTML = editor.getHTML()
			console.log "here"
			console.log newHTML

			# Do something to update the edited value provided by the Froala-Editor plugin, if it has changed:
			unless _.isEqual(newHTML, self.someSalad.description)
				console.log "onSave HTML is :" + newHTML
				Salad.update
					_id: self.someSalad._id
				,
					$set:
						description: newHTML

			false # Stop Froala Editor from POSTing to the Save URL

		return


the save is triggering ok from 
    <div>
           {{> froalaReactive inlineMode=false _onbeforeSave=doSave _value=someSalad.description}}
    </div>

**Comment by rjsmith** [comment]
Hi,

I am not familiar with coffeescript syntax, but it looks like your code is not actually returning the (anonymous) function declared in the handler, because the final `return` with no arguments ensures that the coffeescript compiler does not generate a return statement in the output javascript?

**Comment by payner35** [comment]
ok... think i got this figured out...

it works fine for a '_onblur' event but not the  '_onbeforeSave" event.. 

I am assuming this is because the collection.update is happening on the sever side.. and not the client ;)

this is causing the scope issue in the helper.
