### ISSUE TITLE
froala-reactive tutorial

### ISSUE THREAD

**Issue by abtx** [froala/froala-reactive#8]
Hi, 
first of all thanks for creating this repo. It allows novice meteor users like myself to fiddle with code and learn new amazing stuff. I've got a request for a bit more detailed instructions, if that's possible. I came into a bump with figuring out how use data from my collections looped on page and presented as Froala editable content, and saved back to the collection after edit . A little more instructions will be much appreciated. Thanks.

**Comment by rjsmith** [comment]
Hi,

I am glad you have found Froala-Reactive useful.

Have you read the [Basic Usage](https://github.com/froala/froala-reactive/blob/master/README.md#basic-usage) section of the README?  It describes the basic pattern of setting the `_value` attribute to a text field in your template's data context (e.g. a field in a collection document), and then providing a `_onbeforeSave` callback function that you can use to update the collection document field's content.  The example does assume you are reasonably familiar with Meteor itself.  Is there anything in the README you do not understand? Let me know here, maybe I can improve it (e.g. add more links to Meteor docs), without writing a complete Meteor tutorial!

I am a bit time-constrained at the moment.  The more specific you can be about the "bump" you have encountered, the easier it will be for me to help.  Can you post some minimal - viable code here that reproduces the issue(s) you have encountered?

**Comment by abtx** [comment]
Hi, 

thanks for quick reply. I appreciate you found time to answer this. Answering your questions, yes, I have followed instructions from README, the _onbeforeSave was not working (no console.log) and when changed to _onblur I got an error. I have collections, subscribtions, etc. set up correctly in my Meteor project. I'm a newbie to Meteor, so this could be something prosaic, but I think I grasped the basics from discover meteor book and some tutorials. I cannot figure out how _value=myDoc.myHTMLField is supposed to work. Is myDoc.myHTML a key:value in myCollection?  Also, I don't quite get how {{> froalaReactive _onblur=doSave _value=myDoc.myHTMLField}} can loop through all the values in myCollection and output them. 
Perhaps my understanding that simply by having a collection with key:value that maps to _value=myDoc.myHTML is what is causing the problem? 
If you could point me in the right direction that'd be a huge help.

**Comment by rjsmith** [comment]
Suppose you have a helper that returns a collection cursor:
```javascript
Template.myTemplate.helpers({
  getCollectionDocuments: function () {
    return aCollection.find();
  },

  doSave: function() {
    var self = this; // 'self' has the data context inside the #each block ie. one document in the aCollection collection
    return function (e, editor) {
      // Get edited HTML from Froala-Editor
      var newHTML = editor.getHTML();
      // Do something to update the edited value provided by the Froala-Editor plugin, if it has changed:
      if (!_.isEqual(newHTML, self.description)) {
        console.log("onSave HTML is :"+newHTML);
        myCollection.update({_id: self._id}, {
          $set: {description: newHTML}
        });
      }
      return false; // Stop Froala Editor from POSTing to the Save URL
});
```

Let's say that each document within the collection has a field `description` that you want to be able to edit in a Froala Editor widget.   Then you need to write a template something like:

```html
<template name="myTemplate">
  {{#each getCollectionDocuments}}
    {{> froalaReactive _onblur=doSave _value=description}}
  {{/each}}
</template>
```

fyi - I haven't tried this exact code myself, just typed it into the comment field, so may have some syntax errors!  Hope that points you in the right direction.

**Comment by abtx** [comment]
I see, I think I understand now. I tie to the collection simply by using the template helper, then use the key of collection to output its _value. On doSave, I update that very collection (self) at the right place (by _id). That makes sense now. Thanks a lot for the help! Much appreciated!
